### ISSUE TITLE
Suport for the Complex Lit Shader

### ISSUE THREAD

**Issue by rroyermoraes** [JoshuaLim007/Unity-ScreenSpaceReflections-URP#15]
I'm working on a project where I need the Clear Coat component from the Complex Lit Shader. There is any way to make the reflections work on this shader variant?

**Comment by JoshuaLim007** [comment]
From Unity Docs:
**"Complex Lit: the Lighting model of this shader (for example, the Clear Coat effect) is too complex and extra Material properties cannot fit into the G-buffer."** 

It seems like clear coats are a forward only pass. This SSR solutions was specifically designed for the deferred rendering mode as it is a post process effect. So I don't think this is possible.

[See here for Unity Docs](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@12.0/manual/rendering/deferred-rendering-path.html)
