### ISSUE TITLE
smoothness reflection look weird

### ISSUE THREAD

**Issue by DanielHong120** [JoshuaLim007/Unity-ScreenSpaceReflections-URP#16]
smoothness reflection look like reduce reflection Alpha not blur reflection

**Comment by JoshuaLim007** [comment]
This SSR solution doesn't use cone tracing reflection. Meaning it doesn't actually blur anything for glossy reflections. This solution just lowers the opacity of the reflections along with offsetting the reflection pixels using dithering. It also samples reflections from a lower resolution similar to reflection probes. This solution works best for materials with higher smoothness values with normal maps. This method is much faster at the cost of quality. And also I just don't have the time to implement a proper glosys reflection solution.
