### ISSUE TITLE
Webgl

### ISSUE THREAD

**Issue by crazyalok** [JoshuaLim007/Unity-ScreenSpaceReflections-URP#17]
Hey 

I am unable to see ssr effect with the webgl build. Can you please confirm if this works with webgl build?

Thanks

**Comment by JoshuaLim007** [comment]
Seems like webgl doesn't support deferred rendering, so this ssr effect would not work.

> The Deferred Rendering Path has the following requirements and limitations on top of the general system requirements for the Unity Player.
> 
> Minimum Shader Model: Shader Model 4.5.
> 
> Deferred Rendering Path does not support the OpenGL-based graphics API: Desktop OpenGL, OpenGL ES 2.0, OpenGL ES 3.0, WebGL 1.0, WebGL 2.0.

[Source](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@12.0/manual/rendering/deferred-rendering-path.html)
