### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Milk-Drinker01** [JoshuaLim007/Unity-ScreenSpaceReflections-URP#2]
in the highlighted code in the screenshot, i think you mean to use Settings.SSR_Instance instead of Settings.SSRFragmentShader :)

![Screenshot_2](https://user-images.githubusercontent.com/59656122/227409537-ac28e81b-3044-44e6-b6ab-f164bd83b798.png)

**Comment by JoshuaLim007** [comment]
Yup your correct! Will fix that!
