### ISSUE TITLE
Not working with Accurate G-buffer normals turned on after Build

### ISSUE THREAD

**Issue by Milk-Drinker01** [JoshuaLim007/Unity-ScreenSpaceReflections-URP#3]
I tried to fix this myself, since theoretically it should be simple enough. see the code below:

![Screenshot_8](https://user-images.githubusercontent.com/59656122/227744661-856e4b7b-3631-413c-908f-ab4bd47ae527.png)
(https://github.com/Unity-Technologies/Graphics/blob/master/Packages/com.unity.render-pipelines.universal/ShaderLibrary/UnityGBuffer.hlsl)

However, when trying to simply return the normal, i get bad results:

![Screenshot_9](https://user-images.githubusercontent.com/59656122/227744707-e24432c3-76f6-4a5e-ac20-fcbb2cc60884.png)
![Screenshot_10](https://user-images.githubusercontent.com/59656122/227744708-6b0c9711-9359-46a0-a487-e3a2638a4bca.png)

Maybe you might have a better idea on what needs to be done. ive done similar things in HDRP but im not a URP expert!

**Comment by JoshuaLim007** [comment]
Interesting, I will look into tit.

**Comment by SamFZGames** [comment]
Sorry but I'm gonna have to request this one re-opened. With Accurage G-buffer normals turned on it now works in the editor but not in a build. If I turn them back off again the build works fine, but with them switched on, the SSR doesn't appear in builds.

**Comment by Milk-Drinker01** [comment]
Hello, 
Ive just tested on 2022.2.12, and it seems to be working fine there. Some people had issues with accurate g-buffer normals in previous versions (I had the exact same issue as https://issuetracker.unity3d.com/issues/nothing-is-rendered-in-the-built-urp-project-when-deferred-rendering-is-selected-and-accurate-g-buffer-normals-are-enabled). 

If you are on a version where this issue has been fixed, try searching for incompatibilities with other renderer features.
