### ISSUE TITLE
Reflect sky issue in Hi Z

### ISSUE THREAD

**Issue by RensbourroTaki** [JoshuaLim007/Unity-ScreenSpaceReflections-URP#31]
Hi 1st of all 1000 thanks for this - as it seems - only available and awesome URP SSR solution! 

I have just one issue. The Hi-Z Trace mode causes only to render one half of the sphere/cubemap/skybox. Only 180 degree in the Z+ direction is showing the bright sky. The other 180 degree which is Z- axis is not reflected or to say cut off. My game for example is complete build to run in the Z axis, with a 90 degree camera side view, like in a 2D platformer game. So there is one dark side on the left and on the other half at the right the birght reflected sky. A workaround would be to be able to have a value to rotate the sky render view, if that is technically possible?  

Sadly my whole game (level design/camera & character controller) is built already that way. Else, I would need to turn everything to 90 degree to get around that problem. The screenshot is just a simple scene that I created for this purpose to show the issue. 

![Capture](https://github.com/JoshuaLim007/Unity-ScreenSpaceReflections-URP/assets/123490511/caa81873-c92f-46a1-874c-786c56d22ba7)

**Comment by RensbourroTaki** [comment]
I found in the readme a donation link, so I made a small contribution. Alle the best, Patrick

**Comment by JoshuaLim007** [comment]
Hey! Which unity version and URP version is this occurring in? Also, what GPU model do you have?

**Comment by RensbourroTaki** [comment]
I don't think this has much to do with the graphics card or the URP version. It could be the seam of the reflected sphere/box that you genereate when all sides are coming together. Or it is the usual -90 degree problem, which is an engine problem and can be eradicated with URP features. I can't explain that better, but it's something that unity causes it and people found ways to skip that. Read once a blog article about it. It has something to do with the minus axis, and caused many problems in the old days, when unity had its own issues with transparencies and other correlated features, exactly when the camera moves in the minus direction! However, you can replicate the issue by rotating the camera in your project to -90 in Y axis, or simply look 90 degree left! However, I use URP 14.0.10 and a RTX3090.

**Comment by JoshuaLim007** [comment]
Hey! I found a bug when I was looking through the shader code and updated the main branch with the fix. I wasn't entirely able to replicate this issue, but I'm hoping the bug I just fixed would also resolve this issue. There was a back face cull check in the shader code that was running regardless of if the intersected point was the sky, resulting in undefined behavior.
